Repository borgia-app/Borgia, pull requests merged in 2018-02, with the labels that each got.

#17 Various fix - Merge of module workboard templates
  modules/templates/modules/shop_module_sale_workboard.html
  modules/templates/modules/shop_module_selfsale_workboard.html
  modules/views.py
  static/static_dirs/less/main.less
  templates/login.html
  users/forms.py
  users/templates/users/user_quick_search.html
Labels: bug, enhancement

#16 Negative stock value
  shops/models.py
  shops/views.py
  stocks/forms.py
  stocks/views.py
Labels: bug, enhancement

#19 Handle (ZeroDivisionError, DivisionUndefined, DivisionByZero)
  modules/models.py
  shops/models.py
  shops/views.py
  stocks/views.py
Labels: bug, critical, good first issue

#22 Rex shared event
  borgia/urls.py
  borgia/utils.py
  finances/forms.py
  finances/models.py
  finances/templates/finances/js/ajax_ponderation.html
  finances/templates/finances/js/calculate_users_price.html
  finances/templates/finances/sharedevent_finish.html
  finances/templates/finances/sharedevent_list.html
  finances/templates/finances/sharedevent_manage_users.html
  finances/templates/finances/sharedevent_update.html
  finances/tests.py
  finances/views.py
  shops/models.py
  static/static_dirs/js/sharedevent_finish.js
  users/fixtures/initial.json
Labels: enhancement

#27 Transaction color & sign in user retrieve
  users/templates/users/retrieve.html
Labels: bug, enhancement

#23 Application settings
  borgia/settings.py
  borgia/urls.py
  borgia/utils.py
  finances/forms.py
  finances/templates/finances/self_lydia_button.html
  finances/views.py
  settings_data/fixtures/settings.json
  settings_data/form.py
  settings_data/forms.py
  settings_data/models.py
  settings_data/templates/settings_data/balance_config.html
  settings_data/templates/settings_data/center_config.html
  settings_data/templates/settings_data/global_config.html
  settings_data/templates/settings_data/lydia_config.html
  settings_data/templates/settings_data/price_config.html
  settings_data/utils.py
  settings_data/views.py
  templates/base_clean.html
  templates/base_sober.html
  users/fixtures/initial.json
  users/templatetags/users_extra.py
Labels: enhancement

#28 Migrate to Django 2
  borgia/settings.py
  borgia/urls.py
  borgia/utils.py
  borgia/views.py
  contrib/models.py
  finances/views.py
  notifications/context_processors.py
  notifications/views.py
  requirements.txt
  users/views.py
Labels: Migration, critical, enhancement

#31 Setting purchase down limit
  borgia/settings.py
  modules/forms.py
  modules/views.py
  settings_data/forms.py
  settings_data/templates/settings_data/balance_config.html
  settings_data/templates/settings_data/global_config.html
  settings_data/views.py
  shops/models.py
  shops/templates/shops/product_update_price.html
  shops/views.py
Labels: bug, enhancement
